
version: '3'
services:
  db:
    
    image: mysql:5.7

    ports:
      - '3306:3306'
    
    environment:
      MYSQL_DATABASE: 'injazati'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'

    volumes:
      - ./docker-entrypoint-initdb.d/init.sql:/flask-blog-poc/docker-entrypoint-initdb.d/10-init.sql

    expose:
      - '5432'  

  web:

    build: .   

    ports:
      - 8085:8085
    
    volumes:
      - .:/flask-blog-poc
    
    depends_on:
      - flaskapp-postgres
      
    environment:
      - DATABASE_NAME=blog
      - DATABASE_USER=postgres
      - DATABASE_PASS=admin123
      - DATABASE_HOST=flaskapp-postgres
      - DATABASE_PORT=5432
    
    expose:
