
version: '3'
services:
  db:
    
    image: mysql:5.7

    ports:
      - '3306:3306'
    
    environment:
      MYSQL_DATABASE: 'injazati'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root123'
      MYSQL_ROOT_PASSWORD: 'root123'

    expose:
      - '3307'  

  rest_api:

    build: .   

    ports:
      - 8000:8000
    
    volumes:
      - .:/injazati
    
    depends_on:
      - db
    
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"  
    
    environment:
      - DATABASE_NAME=injazati
      - DATABASE_USER=root
      - DATABASE_PASS=root123
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
